version: '3.1'
services:
  solr:
    image: solr:8.3.1
    command: bash -c '/opt/solr/bin/solr start -f'
    ports:
      - "8983:8983"
    container_name: opt-locking
    volumes:
      - ./src/main/resources/solr-core:/var/solr/data/nrt-search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    ports:
      - "9200:9200"
    container_name: opt-locking
    environment:
      - discovery.type=single-node